// Build status types
export type BuildStatus = 'planning' | 'building' | 'testing' | 'deploying' | 'complete' | 'error';

// Action button type
export interface Action {
  label: string;
  type: 'primary' | 'secondary' | 'link';
  action: string;
}

// Chat message type
export interface ToolUse {
  toolName: string;
  toolId: string;
  input?: Record<string, unknown>;
  result?: unknown;
  approvalStatus?: 'pending' | 'approved' | 'denied';
  description?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'fable';
  content: string;
  timestamp: string;
  metadata?: {
    status?: BuildStatus;
    progress?: number;
    checkmarks?: string[];
    actions?: Action[];
    toolUses?: ToolUse[];
    isStreaming?: boolean;
    buildId?: string;
  };
}

// Log entry type
export interface LogEntry {
  id: string;
  timestamp: string;
  level: 'info' | 'warn' | 'error';
  message: string;
}

// Project type
export interface Project {
  id: string;
  name: string;
  status: BuildStatus;
  createdAt: string;
}

// Chat state type
export interface ChatState {
  messages: ChatMessage[];
  isBuilding: boolean;
  currentBuildId: string | null;
  conversationId: string | null;
  logs: LogEntry[];
}

// UI state type
export interface UIState {
  sidebarOpen: boolean;
  detailsExpanded: boolean;
}

// Conditional field visibility (show/hide form fields based on another field's value)
export interface FieldCondition {
  field: string;
  equals?: string | string[] | boolean;
  notEquals?: string | string[] | boolean;
}

// Per-row action button for list display
export interface ListItemAction {
  label: string;
  icon?: string;
  color?: string;
  actionArgs: Record<string, unknown>;
}

// List display configuration
export interface ListDisplayConfig {
  itemsField: string;
  title: string;
  subtitle?: string;
  caption?: string;
  icon?: string | { field: string };
  badge?: { field: string; colorMap?: Record<string, string> };
  actions?: ListItemAction[];
  emptyMessage?: string;
}

// Form field definition
export interface FormField {
  key: string;
  label?: string;
  placeholder?: string;
  widget?: 'text' | 'textarea' | 'number' | 'select' | 'toggle' | 'slider' | 'multiselect' | 'date' | 'color';
  options?: Array<{ label: string; value: string }>;
  min?: number;
  max?: number;
  step?: number;
  defaultValue?: unknown;
  help?: string;
  showIf?: FieldCondition;
}

// Result display configuration
export interface ResultDisplay {
  type: 'json' | 'cards' | 'table' | 'text' | 'list';
  cards?: Array<{
    field: string;
    label: string;
    format?: 'number' | 'text' | 'badge' | 'percent';
    icon?: string;
  }>;
  columns?: Array<{
    key: string;
    label: string;
  }>;
  list?: ListDisplayConfig;
  summaryTemplate?: string;
}

// Tab definition for tabbed layout
export interface TabDefinition {
  key: string;
  label: string;
  icon?: string;
  form?: { fields: FormField[]; submitLabel?: string };
  resultDisplay?: ResultDisplay;
  defaultArgs?: Record<string, unknown>;
  autoRefreshAfter?: string[];
  autoInvoke?: boolean;
}

// Tool UI Definition (generated by builder, rendered dynamically by frontend)
export interface ToolUIDefinition {
  title: string;
  subtitle?: string;
  icon?: string;
  layout?: 'simple' | 'tabs';
  tabs?: TabDefinition[];
  stateKey?: string;
  form: {
    fields: FormField[];
    submitLabel?: string;
  };
  resultDisplay: ResultDisplay;
  examples?: Array<{
    label: string;
    input: Record<string, unknown>;
  }>;
}

// Tool record (from MCP Gateway)
export interface FableTool {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  uiDefinition?: ToolUIDefinition;
}

// Workflow definition (from builder output / MCP API)
export interface WorkflowDefinition {
  workflowId: string;
  name: string;
  description: string;
  prompt: string;
  tools?: string[];
  trigger: {
    type: 'manual' | 'cron';
    schedule?: string;
    timezone?: string;
  };
  model?: 'haiku' | 'sonnet';
  maxTurns?: number;
  status: 'active' | 'paused' | 'completed';
  orgId: string;
  executionCount?: number;
  lastExecutedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

// Conversation summary (for sidebar listing)
export interface ConversationSummary {
  conversationId: string;
  title: string;
  updatedAt: string;
  intent?: string;
}

// Full conversation (loaded from backend)
export interface ConversationFull {
  conversationId: string;
  title: string;
  messages: Array<{ role: string; content: string; timestamp: string }>;
  activeBuildId: string | null;
  updatedAt: string;
}

// Build record (from DynamoDB — list view)
export interface BuildRecord {
  buildId: string;
  status: 'pending' | 'retrying' | 'completed' | 'failed' | 'needs_help';
  request: string;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;
  buildCycle?: number;
  userId?: string;
}

// Build detail record (from DynamoDB — full view with QA)
export interface BuildDetailRecord extends BuildRecord {
  parentBuildId: string | null;
  resolvedByBuildId: string | null;
  conversationId: string | null;
  deployedTools: Array<{ toolName: string; functionName?: string }>;
  workflows: Array<{ name: string; workflowId: string }>;
  qa: {
    smokeTests: Array<{
      toolName: string;
      allPassed: boolean;
      testCases: Array<{
        description: string;
        passed: boolean;
        error: string | null;
        expectedOutput: unknown;
        actualOutput: unknown;
      }>;
    }>;
    fidelity: { pass: boolean; reasoning: string; gaps: string[] } | null;
    uiDefinitionIssues: string[] | null;
    visualQaIssues: string[] | null;
    uxScores: { discoverability: number; ease_of_use: number; result_clarity: number; average: number } | null;
    uxCritique: string | null;
    uxSuggestions: string[] | null;
  };
  failureContext: {
    smokeTestFailures: unknown[];
    fidelityGaps: string[];
    fidelityReasoning: string;
  } | null;
  error: string | null;
}

// Memory record (from Aurora via Memory Lambda)
export interface MemoryRecord {
  id: string;
  type: string;
  content: string;
  scope: string;
  importance: number;
  pinned: boolean;
  tags: string[];
  createdAt: string;
}

// Notification record (from DynamoDB)
export interface FableNotification {
  userId: string;
  notifId: string;
  type: 'build_completed' | 'build_failed' | 'build_needs_help';
  title: string;
  message: string;
  metadata: Record<string, unknown>;
  read: boolean;
  createdAt: string;
}

// WebSocket message types (outgoing to server)
export interface WsOutgoingMessage {
  type: 'message' | 'ping' | 'list_conversations' | 'load_conversation' | 'delete_conversation' | 'list_builds' | 'get_build' | 'list_memories' | 'delete_memory' | 'list_notifications' | 'mark_notifications_read';
  payload?: {
    content?: string;
    conversationId?: string;
    memoryId?: string;
    approvedTools?: string[];
    buildId?: string;
  };
}

// Build progress (real-time streaming from ECS builder)
export interface BuildProgressPayload {
  buildId: string;
  phase: string;
  message: string;
  progress?: number;
  iteration?: number;
  maxIterations?: number;
  timestamp: string;
}

// WebSocket message types (incoming from server)
export type WsIncomingMessage =
  | { type: 'chat_chunk'; payload: { messageId: string; content: string } }
  | { type: 'chat_response'; payload: { messageId: string; content: string } }
  | { type: 'chat_complete'; payload: { messageId: string; fullContent: string; conversationId: string } }
  | { type: 'build_started'; payload: { buildId: string; toolName: string } }
  | { type: 'build_completed'; payload: { buildId: string; tools: Array<{ toolName: string; functionUrl: string; schema: unknown }> } }
  | { type: 'build_failed'; payload: { buildId: string; error: string } }
  | { type: 'build_needs_help'; payload: { buildId: string; message: string } }
  | { type: 'build_progress'; payload: BuildProgressPayload }
  | { type: 'tool_use'; payload: { toolName: string; toolId: string; messageId: string; input?: Record<string, unknown> } }
  | { type: 'tool_result'; payload: { toolId: string; result: unknown; messageId: string } }
  | { type: 'tool_approval_request'; payload: { toolName: string; toolId: string; messageId: string; input?: Record<string, unknown>; description?: string } }
  | { type: 'conversations_list'; payload: { conversations: ConversationSummary[] } }
  | { type: 'conversation_loaded'; payload: ConversationFull }
  | { type: 'conversation_deleted'; payload: { conversationId: string } }
  | { type: 'builds_list'; payload: { builds: BuildRecord[] } }
  | { type: 'build_detail'; payload: { build: BuildDetailRecord } }
  | { type: 'memories_list'; payload: { memories: MemoryRecord[] } }
  | { type: 'memory_deleted'; payload: { memoryId: string; success: boolean } }
  | { type: 'notifications_list'; payload: { notifications: FableNotification[] } }
  | { type: 'notifications_updated' }
  | { type: 'pong'; timestamp: string }
  | { type: 'error'; message: string };
