// Build status types
export type BuildStatus = 'planning' | 'building' | 'testing' | 'deploying' | 'complete' | 'error';

// Action button type
export interface Action {
  label: string;
  type: 'primary' | 'secondary' | 'link';
  action: string;
}

// Chat message type
export interface ToolUse {
  toolName: string;
  toolId: string;
  input?: Record<string, unknown>;
  result?: unknown;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'fable';
  content: string;
  timestamp: string;
  metadata?: {
    status?: BuildStatus;
    progress?: number;
    checkmarks?: string[];
    actions?: Action[];
    toolUses?: ToolUse[];
  };
}

// Log entry type
export interface LogEntry {
  id: string;
  timestamp: string;
  level: 'info' | 'warn' | 'error';
  message: string;
}

// Project type
export interface Project {
  id: string;
  name: string;
  status: BuildStatus;
  createdAt: string;
}

// Chat state type
export interface ChatState {
  messages: ChatMessage[];
  isBuilding: boolean;
  currentBuildId: string | null;
  conversationId: string | null;
  logs: LogEntry[];
}

// UI state type
export interface UIState {
  sidebarOpen: boolean;
  detailsExpanded: boolean;
}

// Tool UI Definition (generated by builder, rendered dynamically by frontend)
export interface ToolUIDefinition {
  title: string;
  subtitle?: string;
  icon?: string;
  form: {
    fields: Array<{
      key: string;
      label?: string;
      placeholder?: string;
      widget?: 'text' | 'textarea' | 'number' | 'select' | 'toggle' | 'slider';
      options?: Array<{ label: string; value: string }>;
      min?: number;
      max?: number;
      step?: number;
      defaultValue?: unknown;
      help?: string;
    }>;
    submitLabel?: string;
  };
  resultDisplay: {
    type: 'json' | 'cards' | 'table' | 'text';
    cards?: Array<{
      field: string;
      label: string;
      format?: 'number' | 'text' | 'badge' | 'percent';
      icon?: string;
    }>;
    columns?: Array<{
      key: string;
      label: string;
    }>;
    summaryTemplate?: string;
  };
  examples?: Array<{
    label: string;
    input: Record<string, unknown>;
  }>;
}

// Tool record (from MCP Gateway)
export interface FableTool {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  uiDefinition?: ToolUIDefinition;
}

// Workflow definition (from builder output / MCP API)
export interface WorkflowDefinition {
  workflowId: string;
  name: string;
  description: string;
  prompt: string;
  tools?: string[];
  trigger: {
    type: 'manual' | 'cron';
    schedule?: string;
    timezone?: string;
  };
  model?: 'haiku' | 'sonnet';
  maxTurns?: number;
  status: 'active' | 'paused' | 'completed';
  orgId: string;
  executionCount?: number;
  lastExecutedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

// Conversation summary (for sidebar listing)
export interface ConversationSummary {
  conversationId: string;
  title: string;
  updatedAt: string;
  intent?: string;
}

// Full conversation (loaded from backend)
export interface ConversationFull {
  conversationId: string;
  title: string;
  messages: Array<{ role: string; content: string; timestamp: string }>;
  activeBuildId: string | null;
  updatedAt: string;
}

// WebSocket message types (outgoing to server)
export interface WsOutgoingMessage {
  type: 'message' | 'ping' | 'list_conversations' | 'load_conversation' | 'delete_conversation';
  payload?: {
    content?: string;
    conversationId?: string;
  };
}

// WebSocket message types (incoming from server)
export type WsIncomingMessage =
  | { type: 'chat_response'; payload: { messageId: string; content: string } }
  | { type: 'chat_complete'; payload: { messageId: string; fullContent: string; conversationId: string } }
  | { type: 'build_started'; payload: { buildId: string; toolName: string } }
  | { type: 'build_completed'; payload: { buildId: string; tools: Array<{ toolName: string; functionUrl: string; schema: unknown }> } }
  | { type: 'build_failed'; payload: { buildId: string; error: string } }
  | { type: 'build_needs_help'; payload: { buildId: string; message: string } }
  | { type: 'tool_use'; payload: { toolName: string; toolId: string; messageId: string; input?: Record<string, unknown> } }
  | { type: 'tool_result'; payload: { toolId: string; result: unknown; messageId: string } }
  | { type: 'conversations_list'; payload: { conversations: ConversationSummary[] } }
  | { type: 'conversation_loaded'; payload: ConversationFull }
  | { type: 'conversation_deleted'; payload: { conversationId: string } }
  | { type: 'pong'; timestamp: string }
  | { type: 'error'; message: string };
