/**
 * Tool Loader
 *
 * This file imports all tool files to trigger their self-registration.
 * When you add a new tool, add an import line here.
 *
 * IMPORTANT: This is the ONLY file that needs to be modified when adding
 * new tools. Each tool file handles its own registration via registerTool().
 *
 * For auto-generated servers, this file can be generated by scanning
 * the tools directory and importing all .ts files.
 */

// Import tools to trigger registration
import './example.js';

// Add new tool imports here:
// import './my-new-tool.js';
